# This is a basic workflow to help you get started with Actions

name: GitHub Classroom Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - '*'
    - '!badges'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Autograding
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: path
        run: |
          push.sh ${{ github.actor }} $(pwd) ${{ steps.autograder.outputs.Points }} sql_using_array
        continue-on-error: true


      # make dir for badges
      - name: badges branch and make dir
        run: |
          git checkout badges || git checkout -b badges
          mkdir -p .github/badges
        continue-on-error: true

      - name: show points
        run: echo ${{ steps.autograder.outputs.Points }}
        continue-on-error: true
        
      # make points badge
      - name: points badge
        uses: emibcn/badge-action@v1
        with:
          LABEL: 'Points'
          STATUS: ${{ steps.autograder.outputs.Points }}
          COLOR: cyan
          path: '.github/badges/points.svg'

        # commit and push badge if score has changed
      - name: Commit badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/badges/points.svg'
          git commit -m "Add/Update badge"
        continue-on-error: true
        
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: badges
          force: true
        continue-on-error: true

      # fail job if autograder returns failed
      # outcome can be 'success', 'failure', 'cancelled', or 'skipped'
      # trigger fail either on !success or on failure depending on preference
      - name: check autograder pass fail
        if: ${{ steps.autograder.outcome != 'success' }}
        # if: ${{ steps.autograder.outcome == 'failure' }}
        # if: ${{ failure }}
        run: exit 1        
